addEventListener('load',()=>setTimeout(async()=>{const results=[];async function test(name,fn){try{const data=await fn();results.push({test:name,ok:data===true,detail:data});}catch(e){results.push({test:name,ok:false,error:e.message});}}
 await test('Inicialização e versão',()=>typeof Chess==='function' && xpBuildInfo.appVersion==='19.0.0');
 await test('Mate local imediato e finalização idempotente',()=>{startGame('pvp');soundEnabled=false;voiceNarrEnabled=false;const stats=xpGetStats().games;for(const san of ['f3','e5','g4','Qh4#'])finalizeLocalMove(chess.move(san));const n=xpGetStats().games;checkGameStateEvents(false);handleGameOverEvents('duplicado','b');return gameOverHandled && document.getElementById('victory-screen').style.display==='flex' && n===stats+1 && xpGetStats().games===n;});
 await test('Mate IA e Elo único',()=>{startGame('pve');playerColor='w';for(const m of ['f3','e5','g4']){chess.move(m);recordMoveHistoryPosition();}applyAIMove({from:'d8',to:'h4'});const elo=playerElo;applyEloAfterGame('b');return gameOverHandled && chess.in_checkmate() && playerElo===elo;});
 await test('Afogamento',()=>{startGame('pvp');chess.load('7k/5Q2/6K1/8/8/8/8/8 b - - 0 1');checkGameStateEvents(false);return gameOverHandled && /Afogamento/.test(document.getElementById('victory-subtitle').textContent);});
 await test('Material insuficiente',()=>{startGame('pvp');chess.load('7k/8/6K1/8/8/8/8/8 w - - 0 1');return checkGameStateEvents(false)&&gameOverHandled;});
 await test('50 lances e prioridade de mate',()=>{startGame('pvp');chess.load('7k/8/6K1/8/8/8/8/R7 w - - 100 51');checkGameStateEvents(false);const draw=/50 lances/.test(document.getElementById('victory-subtitle').textContent);resetGame();chess.load('7k/6Q1/5K2/8/8/8/8/8 b - - 100 51');checkGameStateEvents(false);return draw&&/Xeque-mate/.test(document.getElementById('victory-subtitle').textContent);});
 await test('Repetição oficial preservada; posição equilibrada continua',()=>{startGame('pvp');if(checkGameStateEvents(false))return false;for(const m of ['Nf3','Nf6','Ng1','Ng8','Nf3','Nf6','Ng1','Ng8'])chess.move(m);return checkGameStateEvents(false)&&chess.in_threefold_repetition();});
 await test('Undo PvE durante turno IA',async()=>{startGame('pve');playerColor='w';chess.move('e4');recordMoveHistoryPosition();const old=customConfirm;customConfirm=async()=>true;const request=aiRequestId;await safeUndoMove();customConfirm=old;return chess.history().length===0 && chess.turn()==='w' && aiRequestId>request && moveHistoryFens.length===1;});
 await test('Undo PvE depois da resposta e bloqueio pós-final',async()=>{startGame('pve');playerColor='w';chess.move('e4');recordMoveHistoryPosition();chess.move('e5');recordMoveHistoryPosition();const old=customConfirm;customConfirm=async()=>true;await safeUndoMove();const empty=chess.history().length===0;chess.move('e4');handleGameOverEvents('Desistência','b');const fen=chess.fen();await safeUndoMove();customConfirm=old;return empty&&fen===chess.fen();});
 await test('Rede lance, ACK, duplicata e hash inválido',()=>{startGame('pvp');gameMode='network';playerColor='b';const sent=[];conn={open:true,send:m=>sent.push(m)};const c=new Chess();const before=c.fen();c.move('e4');const data={type:'move',move:{from:'e2',to:'e4'},fen:c.fen(),hash:xpPositionHash(c.fen()),previousHash:xpPositionHash(before),ply:1,id:'test:1'};handleIncomingConnData(data);handleIncomingConnData(data);const once=chess.history().length===1&&sent.filter(x=>x.type==='move-ack').length===2;playerColor='w';handleIncomingConnData({type:'move',move:{from:'e7',to:'e5'},hash:'bad',ply:2,id:'test:2'});return once&&chess.history().length===1;});
 await test('Mate remoto imediato e duplicata sem Elo extra',()=>{startGame('pvp');gameMode='network';playerColor='w';conn={open:true,send(){}};for(const m of ['f3','e5','g4']){chess.move(m);recordMoveHistoryPosition();}const copy=new Chess();for(const m of ['f3','e5','g4','Qh4#'])copy.move(m);const d={type:'move',move:{from:'d8',to:'h4'},fen:copy.fen(),ply:4,id:'mate'};handleIncomingConnData(d);const elo=playerElo,n=xpGetStats().games;handleIncomingConnData(d);return gameOverHandled&&chess.in_checkmate()&&elo===playerElo&&n===xpGetStats().games;});
 await test('Replay validado, histórico preservado e conflito rejeitado',()=>{startGame('pvp');gameMode='network';playerColor='b';conn={open:true,send(){}};const c=new Chess();c.move('e4');const d={type:'ping',moves:c.history({verbose:true}),plyCount:1,fen:c.fen(),hash:xpPositionHash(c.fen())};handleIncomingConnData(d);const f=chess.fen();handleIncomingConnData({...d,fen:new Chess().fen()});return chess.history().length===1&&chess.fen()===f&&moveHistoryFens.length===2;});
 await test('Undo remoto preserva histórico legal',()=>{startGame('pvp');gameMode='network';conn={open:true,send(){}};for(const m of ['e4','e5']){chess.move(m);recordMoveHistoryPosition();}const before=chess.fen(),c=new Chess();c.move('e4');handleIncomingConnData({type:'undo',count:1,beforeFen:before,fen:c.fen()});return chess.fen()===c.fen()&&chess.history().length===1;});
 await test('Cooldown local e remoto',()=>{let count=0;const old=showFloatingReaction;showFloatingReaction=()=>count++;gameMode='pvp';isSpectator=false;xpLastReaction=-Infinity;xpLastRemoteReaction=-Infinity;sendReaction('🔥');sendReaction('🔥');handleIncomingConnData({type:'reaction',emoji:'🔥'});handleIncomingConnData({type:'reaction',emoji:'🔥'});showFloatingReaction=old;return count===2;});
 await test('Neon independente, geometria e restauração',()=>{startGame('pvp');const model=document.querySelector('.white-piece').style.backgroundImage;xpSetNeon('w','#ec4899');xpSetNeon('b','#3b82f6');const ok=getComputedStyle(document.querySelector('.white-piece')).filter.includes('236, 72, 153')&&getComputedStyle(document.querySelector('.black-piece')).filter.includes('59, 130, 246')&&document.querySelector('.white-piece').style.backgroundImage===model;xpResetNeon();return ok&&!document.body.style.getPropertyValue('--neon-w');});
 await test('net=a4g normalizado',()=>{const old=navigator.connection;Object.defineProperty(navigator,'connection',{value:{effectiveType:'a4g'},configurable:true});const ok=getLogContext().net==='unknown';Object.defineProperty(navigator,'connection',{value:old,configurable:true});return ok;});
const pre=document.createElement('pre');pre.id='test-results';pre.style='position:fixed;inset:0;z-index:999999;background:white;color:black;overflow:auto;padding:20px';pre.textContent=JSON.stringify(results,null,2);document.body.append(pre);},300));